### ISSUE TITLE
CryptoCompare API closed

### ISSUE THREAD

**Issue by cicoub13** [rdegges/cryptocompare#2]
They recommend to use https://min-api.cryptocompare.com/ but no Image inside :(

https://www.cryptocompare.com/api/#
> DUE TO ABUSIVE USAGE, IF YOU WANT YOUR CLIENTS TO DIRECTLY USE OUR APIS, USE THE MIN-API PATH. (THE HEADER Access-Control-Allow-Origin: * is only set on min-api paths)

**Comment by rdegges** [comment]
Oh no. It looks like the guy who runs it changed the terms. Know of any alternatives?

**Comment by cicoub13** [comment]
I looked for it 5 minutes and couldn't find some alternative. I downloaded the pictures from CoinMarket to store it statically.

**Comment by johnnywalters** [comment]
I used request package with node and was able to circumvent the cors messaging. However when trying to do it client side, I get cors errors. It has to do with cryptocompare's API and their headers.
