### ISSUE TITLE
CORS error when trying to access cryptocompare api

### ISSUE THREAD

**Issue by sbley** [rdegges/cryptocompare#8]
That is what the console log shows after loading https://scotch-io.github.io/cryptocompare/

> bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 ()
> scotch-io.github.io/:1 Failed to load https://www.cryptocompare.com/api/data/coinlist: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://scotch-io.github.io' is therefore not allowed access.

I am on Chrome 66.

**Comment by rdegges** [comment]
Just merged in a PR which should fix this.
