### ISSUE TITLE
TypeError: Cannot read property 'ImageUrl' of undefined

### ISSUE THREAD

**Issue by szewah** [rdegges/cryptocompare#9]
@rdegges 
Hello, when I updated coinmarket cap v1 to v2 on line 54 in the app.js file, it threw up this message
"TypeError: Cannot read property 'ImageUrl' of undefined"
On looking further, the coinmarketcap data has been changed from an array to an object.

**Comment by rdegges** [comment]
Want to submit a PR with the changes? I'd be happy to mege!
